In [0]:
# 导入工具包 numpy pandas用于数据处理  
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn import metrics
from sklearn import preprocessing
%matplotlib inline
#装载云盘
from google.colab import drive
drive.mount('/content/drive')

In [0]:
#读取数据
df = pd.read_csv('/content/drive/My Drive/colab/5G_contest/train.csv')
#df = shuffle(df)
train=df.iloc[0:500000,]
test=df.iloc[500000:,]
train.head()

In [0]:
train.shape
train.info()
train['is_5g'].value_counts()

(500000, 60)

In [0]:
from sklearn.preprocessing import StandardScaler
#不用的特征
#进行数据归一化 mu=0 sigma=1
is_5g=df.is_5g
nouse=['area_id','user_id','prov_id','is_5g']
df=df.drop(nouse,axis=1)
df01= StandardScaler().fit_transform(df)
df= pd.DataFrame(df01,columns=df.columns)
df=pd.concat([df,is_5g],axis=1)
df.head()

chnl_type  service_type  product_type  ...  city_5g_ratio  city_level  is_5g
0  -0.077967      0.194582      1.025636  ...       0.025871    0.920834    1.0
1  -0.077967      0.194582     -0.661127  ...      -0.193787   -0.758815    0.0
2  -0.077967      0.194582      0.182255  ...      -0.005174   -0.758815    0.0
3   1.088516      0.194582      1.025636  ...      -0.233636   -1.178727    0.0
4  -0.077967      0.194582     -0.661127  ...       0.474591    0.500922    0.0

[5 rows x 57 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
#不用的特征
#进行数据归一化 mu=0 sigma=1
is_5g=train.is_5g
nouse=['area_id','user_id','prov_id','is_5g']
train=train.drop(nouse,axis=1)
train01= StandardScaler().fit_transform(train)
train= pd.DataFrame(train01,columns=train.columns)
train=pd.concat([train,is_5g],axis=1)
train.head()

chnl_type  service_type  product_type  ...  city_5g_ratio  city_level  is_5g
0  -0.077222      0.194507      1.025662  ...       0.026629    0.919884    1.0
1  -0.077222      0.194507     -0.660076  ...      -0.193061   -0.760030    0.0
2  -0.077222      0.194507      0.182793  ...      -0.004421   -0.760030    0.0
3   1.088542      0.194507      1.025662  ...      -0.232916   -1.180009    0.0
4  -0.077222      0.194507     -0.660076  ...       0.475414    0.499906    0.0

[5 rows x 57 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
#不用的特征
#进行数据归一化 mu=0 sigma=1
y_test=test.is_5g
nouse=['area_id','user_id','prov_id','is_5g']
x_test=test.drop(nouse,axis=1)
x_test01= StandardScaler().fit_transform(x_test)
x_test= pd.DataFrame(x_test01,columns=x_test.columns)
x_test.tail()

chnl_type  service_type  ...  city_5g_ratio  city_level
199995  -0.079835      0.194767  ...      -0.613932    0.923211
199996  -0.079835      0.194767  ...      -0.466287    0.083715
199997   1.088454      0.194767  ...      -0.664400    0.923211
199998   1.088454      0.194767  ...      -0.469962    0.923211
199999  -2.416414      0.194767  ...       0.904107   -1.595279

[5 rows x 56 columns]

In [0]:
## 下采样
# 分离特征和标签
x_train = train.loc[:, train.columns != 'is_5g']
y_train = train['is_5g']
# 计算少数类个数
number_records_is_5g = len(train[train.is_5g == 1])
# 取得少数类样本的索引
is_5g_indices = np.array(train[train.is_5g == 1].index)
# 取得多数类样本的索引
normal_indices = train[train.is_5g == 0].index

# 从多数类中随机选择与少数类个数相同的样本数作为样本
random_normal_indices = np.random.choice(normal_indices, number_records_is_5g, replace = False)
random_normal_indices = np.array(random_normal_indices)

# 合并随机取得的0类和全部的1类的索引
under_sample_indices = np.concatenate([is_5g_indices,random_normal_indices])

# 根据索引得到下采样后的数据集
under_sample_train = train.iloc[under_sample_indices,:]

# 分离特征和标签
x_undersample = under_sample_train.iloc[:, under_sample_train.columns != 'is_5g']
y_undersample = under_sample_train.iloc[:, under_sample_train.columns == 'is_5g']

print("正样本比例(0类): ", len(under_sample_train[under_sample_train.is_5g == 0])/len(under_sample_train))
print("负样本比例(1类): ", len(under_sample_train[under_sample_train.is_5g == 1])/len(under_sample_train))
print("下采样后总样本个数为: ", len(under_sample_train))

正样本比例(0类):  0.5
负样本比例(1类):  0.5
下采样后总样本个数为:  13362


In [0]:
train_data,test_data, train_labels, test_labels=\
x_undersample.values, x_test.values, y_undersample.values, y_test.values

In [0]:
#随机森林方法
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=2, random_state=0)
model.fit(train_data,train_labels)
print("测试集:")
predict_target2=model.predict(test_data)
print("预测正确数量,测试集样本量:")
print(sum(predict_target2 == test_labels),len(test_labels))
print("精确度等指标：")
print(metrics.classification_report(test_labels,predict_target2))
print("混淆矩阵：")
print(metrics.confusion_matrix(test_labels,predict_target2))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


测试集:
预测正确数量,测试集样本量:
145542 200000
精确度等指标：
              precision    recall  f1-score   support

         0.0       1.00      0.73      0.84    197408
         1.0       0.04      0.84      0.07      2592

    accuracy                           0.73    200000
   macro avg       0.52      0.78      0.46    200000
weighted avg       0.98      0.73      0.83    200000

混淆矩阵：
[[143367  54041]
 [   417   2175]]


In [0]:
#logistic回归
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0,l1_ratio=0.01)
model.fit(train_data,train_labels)
print("测试集:")
predict_target2=model.predict(test_data)
print("预测正确数量,测试集样本量:")
print(sum(predict_target2 == test_labels),len(test_labels))
print("精确度等指标：")
print(metrics.classification_report(test_labels,predict_target2))
print("混淆矩阵：")
print(metrics.confusion_matrix(test_labels,predict_target2))


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1501: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  "(penalty={})".format(self.penalty))
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


测试集:
预测正确数量,测试集样本量:
156455 200000
精确度等指标：
              precision    recall  f1-score   support

         0.0       1.00      0.78      0.88    197408
         1.0       0.04      0.74      0.08      2592

    accuracy                           0.78    200000
   macro avg       0.52      0.76      0.48    200000
weighted avg       0.98      0.78      0.87    200000

混淆矩阵：
[[154538  42870]
 [   675   1917]]


In [0]:
from sklearn.ensemble import GradientBoostingClassifier
model =GradientBoostingClassifier(random_state=123)
model.fit(train_data,train_labels)
print("测试集:")
predict_target2=model.predict(test_data)
print("预测正确数量,测试集样本量:")
print(sum(predict_target2 == test_labels),len(test_labels))
print("精确度等指标：")
print(metrics.classification_report(test_labels,predict_target2))
print("混淆矩阵：")
print(metrics.confusion_matrix(test_labels,predict_target2))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


测试集:
预测正确数量,测试集样本量:
157574 200000
精确度等指标：
              precision    recall  f1-score   support

         0.0       1.00      0.79      0.88    197408
         1.0       0.05      0.84      0.09      2592

    accuracy                           0.79    200000
   macro avg       0.52      0.81      0.49    200000
weighted avg       0.99      0.79      0.87    200000

混淆矩阵：
[[155397  42011]
 [   415   2177]]


In [0]:
#使用adaboost分类算法
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(n_estimators=100, random_state=0)
model.fit(train_data,train_labels)
print("测试集:")
predict_target2=model.predict(test_data)
print("预测正确数量,测试集样本量:")
print(sum(predict_target2 == test_labels),len(test_labels))
print("精确度等指标：")
print(metrics.classification_report(test_labels,predict_target2))
print("混淆矩阵：")
print(metrics.confusion_matrix(test_labels,predict_target2))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


测试集:
预测正确数量,测试集样本量:
156467 200000
精确度等指标：
              precision    recall  f1-score   support

         0.0       1.00      0.78      0.88    197408
         1.0       0.05      0.83      0.09      2592

    accuracy                           0.78    200000
   macro avg       0.52      0.81      0.48    200000
weighted avg       0.98      0.78      0.87    200000

混淆矩阵：
[[154317  43091]
 [   442   2150]]
